CREATE TABLE localidadesbogota(
   registro  INTEGER  NOT NULL PRIMARY KEY 
  ,localidad VARCHAR(14) NOT NULL
  ,barrio    VARCHAR(37) NOT NULL
  ,UPZ       VARCHAR(24) NOT NULL
);
UPDATE localidadesbogota SET registro = 1,localidad = 'Usaquen',barrio = 'Altos de Serrezuela',UPZ = 'Verbenal' WHERE registro= 1;
UPDATE localidadesbogota SET registro = 2,localidad = 'Usaquen',barrio = 'Balcones de Vista hermosa',UPZ = 'Verbenal' WHERE registro= 2;
UPDATE localidadesbogota SET registro = 3,localidad = 'Usaquen',barrio = 'Balmoral Norte',UPZ = 'Verbenal' WHERE registro= 3;
UPDATE localidadesbogota SET registro = 4,localidad = 'Usaquen',barrio = 'Bosque de San Antonio',UPZ = 'La Uribe' WHERE registro= 4;
UPDATE localidadesbogota SET registro = 5,localidad = 'Usaquen',barrio = 'El Pite',UPZ = 'La Uribe' WHERE registro= 5;
UPDATE localidadesbogota SET registro = 6,localidad = 'Usaquen',barrio = 'Babilonia',UPZ = 'Tober�n' WHERE registro= 6;
UPDATE localidadesbogota SET registro = 7,localidad = 'Usaquen',barrio = 'Estrella del Norte',UPZ = 'Tober�n' WHERE registro= 7;
UPDATE localidadesbogota SET registro = 8,localidad = 'Usaquen',barrio = 'Antigua',UPZ = 'Los Cedros' WHERE registro= 8;
UPDATE localidadesbogota SET registro = 9,localidad = 'Usaquen',barrio = 'Belmira',UPZ = 'Los Cedros' WHERE registro= 9;
UPDATE localidadesbogota SET registro = 10,localidad = 'Usaquen',barrio = 'El Contador',UPZ = 'Los Cedros' WHERE registro= 10;
UPDATE localidadesbogota SET registro = 11,localidad = 'Chapinero',barrio = 'Chic� Reservado',UPZ = 'El Refugio' WHERE registro= 11;
UPDATE localidadesbogota SET registro = 12,localidad = 'Chapinero',barrio = 'Chic� Alto',UPZ = 'El Refugio' WHERE registro= 12;
UPDATE localidadesbogota SET registro = 13,localidad = 'Chapinero',barrio = 'El Nogal',UPZ = 'El Refugio' WHERE registro= 13;
UPDATE localidadesbogota SET registro = 14,localidad = 'Chapinero',barrio = 'La Sure�a',UPZ = 'San Isidro-Patios' WHERE registro= 14;
UPDATE localidadesbogota SET registro = 15,localidad = 'Chapinero',barrio = 'San Luis',UPZ = 'San Isidro-Patios' WHERE registro= 15;
UPDATE localidadesbogota SET registro = 16,localidad = 'Chapinero',barrio = 'Bosque Calder�n',UPZ = 'Pardo Rubio' WHERE registro= 16;
UPDATE localidadesbogota SET registro = 17,localidad = 'Chapinero',barrio = 'Los Olivos',UPZ = 'Pardo Rubio' WHERE registro= 17;
UPDATE localidadesbogota SET registro = 18,localidad = 'Chapinero',barrio = 'Antiguo Country',UPZ = 'Chic� Lago' WHERE registro= 18;
UPDATE localidadesbogota SET registro = 19,localidad = 'Chapinero',barrio = 'Chic� Norte II',UPZ = 'Chic� Lago' WHERE registro= 19;
UPDATE localidadesbogota SET registro = 20,localidad = 'Chapinero',barrio = 'El Retiro',UPZ = 'Chic� Lago' WHERE registro= 20;
UPDATE localidadesbogota SET registro = 21,localidad = 'Santa Fe',barrio = 'Parque Central Bavaria',UPZ = 'Sagrado Coraz�n' WHERE registro= 21;
UPDATE localidadesbogota SET registro = 22,localidad = 'Santa Fe',barrio = 'San Diego',UPZ = 'Sagrado Coraz�n' WHERE registro= 22;
UPDATE localidadesbogota SET registro = 23,localidad = 'Santa Fe',barrio = 'Samper�',UPZ = 'Sagrado Coraz�n' WHERE registro= 23;
UPDATE localidadesbogota SET registro = 24,localidad = 'Santa Fe',barrio = 'Germania',UPZ = 'La Macarena' WHERE registro= 24;
UPDATE localidadesbogota SET registro = 25,localidad = 'Santa Fe',barrio = 'La Paz Centro',UPZ = 'La Macarena' WHERE registro= 25;
UPDATE localidadesbogota SET registro = 26,localidad = 'Santa Fe',barrio = '�La Capuchina',UPZ = 'Las Nieves' WHERE registro= 26;
UPDATE localidadesbogota SET registro = 27,localidad = 'Santa Fe',barrio = 'La Alameda',UPZ = 'Las Nieves' WHERE registro= 27;
UPDATE localidadesbogota SET registro = 28,localidad = 'Santa Fe',barrio = 'Atanasio Girardot',UPZ = 'Lourdes' WHERE registro= 28;
UPDATE localidadesbogota SET registro = 29,localidad = 'Santa Fe',barrio = 'Cartagena',UPZ = 'Lourdes' WHERE registro= 29;
UPDATE localidadesbogota SET registro = 30,localidad = 'Santa Fe',barrio = 'El Triunfo',UPZ = 'Lourdes' WHERE registro= 30;
UPDATE localidadesbogota SET registro = 31,localidad = 'San Crist�bal',barrio = 'La Casta�a',UPZ = 'San Blas' WHERE registro= 31;
UPDATE localidadesbogota SET registro = 32,localidad = 'San Crist�bal',barrio = 'La Cecilia',UPZ = 'San Blas' WHERE registro= 32;
UPDATE localidadesbogota SET registro = 33,localidad = 'San Crist�bal',barrio = 'Las Acacias',UPZ = 'San Blas' WHERE registro= 33;
UPDATE localidadesbogota SET registro = 34,localidad = 'San Crist�bal',barrio = 'Altos del Poblado',UPZ = 'La Gloria' WHERE registro= 34;
UPDATE localidadesbogota SET registro = 35,localidad = 'San Crist�bal',barrio = 'Buenos Aires',UPZ = 'La Gloria' WHERE registro= 35;
UPDATE localidadesbogota SET registro = 36,localidad = 'San Crist�bal',barrio = 'Quinta Ramos',UPZ = 'Sociego' WHERE registro= 36;
UPDATE localidadesbogota SET registro = 37,localidad = 'San Crist�bal',barrio = '�Los Dos Leones',UPZ = 'Sociego' WHERE registro= 37;
UPDATE localidadesbogota SET registro = 38,localidad = 'San Crist�bal',barrio = 'Barcelona Sur',UPZ = '20 de Julio' WHERE registro= 38;
UPDATE localidadesbogota SET registro = 39,localidad = 'San Crist�bal',barrio = 'Atenas',UPZ = '20 de Julio' WHERE registro= 39;
UPDATE localidadesbogota SET registro = 40,localidad = 'San Crist�bal',barrio = 'Ayacucho',UPZ = '20 de Julio' WHERE registro= 40;
UPDATE localidadesbogota SET registro = 41,localidad = 'Usme',barrio = 'Costa Rica',UPZ = 'La Flora' WHERE registro= 41;
UPDATE localidadesbogota SET registro = 42,localidad = 'Usme',barrio = 'La Caba�a',UPZ = 'La Flora' WHERE registro= 42;
UPDATE localidadesbogota SET registro = 43,localidad = 'Usme',barrio = 'Las Violetas',UPZ = 'La Flora' WHERE registro= 43;
UPDATE localidadesbogota SET registro = 44,localidad = 'Usme',barrio = 'Arrayanes',UPZ = 'Danubio' WHERE registro= 44;
UPDATE localidadesbogota SET registro = 45,localidad = 'Usme',barrio = 'Duitama',UPZ = 'Danubio' WHERE registro= 45;
UPDATE localidadesbogota SET registro = 46,localidad = 'Usme',barrio = 'San Juan Bautista',UPZ = 'Gran Yomasa' WHERE registro= 46;
UPDATE localidadesbogota SET registro = 47,localidad = 'Usme',barrio = 'Olivares',UPZ = 'Gran Yomasa' WHERE registro= 47;
UPDATE localidadesbogota SET registro = 48,localidad = 'Usme',barrio = 'Las Brisas',UPZ = 'Comuneros' WHERE registro= 48;
UPDATE localidadesbogota SET registro = 49,localidad = 'Usme',barrio = 'Las Flores',UPZ = 'Comuneros' WHERE registro= 49;
UPDATE localidadesbogota SET registro = 50,localidad = 'Usme',barrio = 'Las Mercedes',UPZ = 'Comuneros' WHERE registro= 50;
UPDATE localidadesbogota SET registro = 51,localidad = 'Tunjuelito',barrio = 'Abraham Lincoln',UPZ = 'Tunjuelito' WHERE registro= 51;
UPDATE localidadesbogota SET registro = 52,localidad = 'Tunjuelito',barrio = 'San Benito',UPZ = 'Tunjuelito' WHERE registro= 52;
UPDATE localidadesbogota SET registro = 53,localidad = 'Tunjuelito',barrio = 'San Carlos',UPZ = 'Tunjuelito' WHERE registro= 53;
UPDATE localidadesbogota SET registro = 54,localidad = 'Tunjuelito',barrio = 'F�tima',UPZ = 'Venecia' WHERE registro= 54;
UPDATE localidadesbogota SET registro = 55,localidad = 'Tunjuelito',barrio = 'Laguneta',UPZ = 'Venecia' WHERE registro= 55;
UPDATE localidadesbogota SET registro = 56,localidad = 'Tunjuelito',barrio = 'Nuevo Muz�',UPZ = 'Venecia' WHERE registro= 56;
UPDATE localidadesbogota SET registro = 57,localidad = 'Tunjuelito',barrio = 'Rinc�n de Muz�',UPZ = 'Venecia' WHERE registro= 57;
UPDATE localidadesbogota SET registro = 58,localidad = 'Tunjuelito',barrio = 'Samore',UPZ = 'Venecia' WHERE registro= 58;
UPDATE localidadesbogota SET registro = 59,localidad = 'Tunjuelito',barrio = 'Tejar de Ontario',UPZ = 'Venecia' WHERE registro= 59;
UPDATE localidadesbogota SET registro = 60,localidad = 'Tunjuelito',barrio = 'Ciudad Tunal',UPZ = 'Venecia' WHERE registro= 60;
UPDATE localidadesbogota SET registro = 61,localidad = 'Bosa',barrio = 'Jardines del Apogeo',UPZ = 'Apogeo' WHERE registro= 61;
UPDATE localidadesbogota SET registro = 62,localidad = 'Bosa',barrio = 'El Motorista',UPZ = 'Apogeo' WHERE registro= 62;
UPDATE localidadesbogota SET registro = 63,localidad = 'Bosa',barrio = 'Industrial',UPZ = 'Apogeo' WHERE registro= 63;
UPDATE localidadesbogota SET registro = 64,localidad = 'Bosa',barrio = 'La Magnolia',UPZ = 'Bosa Occidental' WHERE registro= 64;
UPDATE localidadesbogota SET registro = 65,localidad = 'Bosa',barrio = 'La Portada',UPZ = 'Bosa Occidental' WHERE registro= 65;
UPDATE localidadesbogota SET registro = 66,localidad = 'Bosa',barrio = 'San Pablo I sector',UPZ = 'Bosa Central' WHERE registro= 66;
UPDATE localidadesbogota SET registro = 67,localidad = 'Bosa',barrio = 'La Estaci�n',UPZ = 'Bosa Central' WHERE registro= 67;
UPDATE localidadesbogota SET registro = 68,localidad = 'Bosa',barrio = 'Caldas',UPZ = 'El Porvenir' WHERE registro= 68;
UPDATE localidadesbogota SET registro = 69,localidad = 'Bosa',barrio = 'Antonio Nari�o',UPZ = 'El Porvenir' WHERE registro= 69;
UPDATE localidadesbogota SET registro = 70,localidad = 'Bosa',barrio = 'El Recuerdo',UPZ = 'El Porvenir' WHERE registro= 70;
UPDATE localidadesbogota SET registro = 71,localidad = 'Kennedy',barrio = 'El Rinc�n de Los �ngeles',UPZ = 'Castilla' WHERE registro= 71;
UPDATE localidadesbogota SET registro = 72,localidad = 'Kennedy',barrio = 'El Tintal',UPZ = 'Castilla' WHERE registro= 72;
UPDATE localidadesbogota SET registro = 73,localidad = 'Kennedy',barrio = 'El Vergel',UPZ = 'Castilla' WHERE registro= 73;
UPDATE localidadesbogota SET registro = 74,localidad = 'Kennedy',barrio = 'Agrupaci�n P�o X',UPZ = 'Am�ricas' WHERE registro= 74;
UPDATE localidadesbogota SET registro = 75,localidad = 'Kennedy',barrio = 'Agrupaci�n Multifamiliar Villa Emilia',UPZ = 'Am�ricas' WHERE registro= 75;
UPDATE localidadesbogota SET registro = 76,localidad = 'Kennedy',barrio = 'Las Torres',UPZ = 'Carvajal' WHERE registro= 76;
UPDATE localidadesbogota SET registro = 77,localidad = 'Kennedy',barrio = 'La Chucua',UPZ = 'Carvajal' WHERE registro= 77;
UPDATE localidadesbogota SET registro = 78,localidad = 'Kennedy',barrio = 'El Jord�n',UPZ = 'Timiza' WHERE registro= 78;
UPDATE localidadesbogota SET registro = 79,localidad = 'Kennedy',barrio = 'Alameda de Timiza',UPZ = 'Timiza' WHERE registro= 79;
UPDATE localidadesbogota SET registro = 80,localidad = 'Kennedy',barrio = 'El Palenque',UPZ = 'Timiza' WHERE registro= 80;
UPDATE localidadesbogota SET registro = 81,localidad = 'Fontib�n',barrio = 'Boh�os',UPZ = 'San Pablo' WHERE registro= 81;
UPDATE localidadesbogota SET registro = 82,localidad = 'Fontib�n',barrio = 'El Tri�ngulo',UPZ = 'San Pablo' WHERE registro= 82;
UPDATE localidadesbogota SET registro = 83,localidad = 'Fontib�n',barrio = 'Florencia',UPZ = 'San Pablo' WHERE registro= 83;
UPDATE localidadesbogota SET registro = 84,localidad = 'Fontib�n',barrio = 'Pueblo Nuevo',UPZ = 'Zona Franca' WHERE registro= 84;
UPDATE localidadesbogota SET registro = 85,localidad = 'Fontib�n',barrio = 'Kasandra',UPZ = 'Zona Franca' WHERE registro= 85;
UPDATE localidadesbogota SET registro = 86,localidad = 'Fontib�n',barrio = 'Carlos Lleras',UPZ = 'Ciudad Salitre Occidente' WHERE registro= 86;
UPDATE localidadesbogota SET registro = 87,localidad = 'Fontib�n',barrio = 'La Esperanza Norte',UPZ = 'Ciudad Salitre Occidente' WHERE registro= 87;
UPDATE localidadesbogota SET registro = 88,localidad = 'Fontib�n',barrio = 'El Franco',UPZ = 'Granjas de Techo' WHERE registro= 88;
UPDATE localidadesbogota SET registro = 89,localidad = 'Fontib�n',barrio = 'Visi�n Semiindustrial',UPZ = 'Granjas de Techo' WHERE registro= 89;
UPDATE localidadesbogota SET registro = 90,localidad = 'Fontib�n',barrio = 'Para�so Bavaria',UPZ = 'Granjas de Techo' WHERE registro= 90;
UPDATE localidadesbogota SET registro = 91,localidad = 'Engativ�',barrio = 'Acapulco',UPZ = 'Las Ferias' WHERE registro= 91;
UPDATE localidadesbogota SET registro = 92,localidad = 'Engativ�',barrio = 'Bellavista Occidental',UPZ = 'Las Ferias' WHERE registro= 92;
UPDATE localidadesbogota SET registro = 93,localidad = 'Engativ�',barrio = 'La Bonanza',UPZ = 'Las Ferias' WHERE registro= 93;
UPDATE localidadesbogota SET registro = 94,localidad = 'Engativ�',barrio = 'Andaluc�a',UPZ = 'Minuto de Dios' WHERE registro= 94;
UPDATE localidadesbogota SET registro = 95,localidad = 'Engativ�',barrio = 'La Palestina',UPZ = 'Minuto de Dios' WHERE registro= 95;
UPDATE localidadesbogota SET registro = 96,localidad = 'Engativ�',barrio = 'Par�s',UPZ = 'Boyac� Real' WHERE registro= 96;
UPDATE localidadesbogota SET registro = 97,localidad = 'Engativ�',barrio = 'Zarzamora',UPZ = 'Boyac� Real' WHERE registro= 97;
UPDATE localidadesbogota SET registro = 98,localidad = 'Engativ�',barrio = 'El Encanto',UPZ = 'Santa Cecilia' WHERE registro= 98;
UPDATE localidadesbogota SET registro = 99,localidad = 'Engativ�',barrio = 'El Lujan',UPZ = 'Santa Cecilia' WHERE registro= 99;
UPDATE localidadesbogota SET registro = 100,localidad = 'Engativ�',barrio = 'San Marcos',UPZ = 'Santa Cecilia' WHERE registro= 100;
UPDATE localidadesbogota SET registro = 101,localidad = 'Suba',barrio = 'Gibraltar',UPZ = 'San Jos� de Bavaria' WHERE registro= 101;
UPDATE localidadesbogota SET registro = 102,localidad = 'Suba',barrio = 'Guicani',UPZ = 'San Jos� de Bavaria' WHERE registro= 102;
UPDATE localidadesbogota SET registro = 103,localidad = 'Suba',barrio = 'Nueva Zelandia',UPZ = 'San Jos� de Bavaria' WHERE registro= 103;
UPDATE localidadesbogota SET registro = 104,localidad = 'Suba',barrio = 'Calima Norte',UPZ = 'Britalia' WHERE registro= 104;
UPDATE localidadesbogota SET registro = 105,localidad = 'Suba',barrio = 'Cantalejo',UPZ = 'Britalia' WHERE registro= 105;
UPDATE localidadesbogota SET registro = 106,localidad = 'Suba',barrio = 'La Esmeralda',UPZ = 'El Rinc�n' WHERE registro= 106;
UPDATE localidadesbogota SET registro = 107,localidad = 'Suba',barrio = 'El Ocal',UPZ = 'El Rinc�n' WHERE registro= 107;
UPDATE localidadesbogota SET registro = 108,localidad = 'Suba',barrio = 'Lisboa',UPZ = 'Tibabuyes' WHERE registro= 108;
UPDATE localidadesbogota SET registro = 109,localidad = 'Suba',barrio = 'La Gaitana',UPZ = 'Tibabuyes' WHERE registro= 109;
UPDATE localidadesbogota SET registro = 110,localidad = 'Suba',barrio = 'Bilbao',UPZ = 'Tibabuyes' WHERE registro= 110;
UPDATE localidadesbogota SET registro = 111,localidad = 'Barrios Unidos',barrio = 'Villa Calasanz',UPZ = 'Los Andes' WHERE registro= 111;
UPDATE localidadesbogota SET registro = 112,localidad = 'Barrios Unidos',barrio = 'Entre R�os',UPZ = 'Los Andes' WHERE registro= 112;
UPDATE localidadesbogota SET registro = 113,localidad = 'Barrios Unidos',barrio = 'La Patria',UPZ = 'Los Andes' WHERE registro= 113;
UPDATE localidadesbogota SET registro = 114,localidad = 'Barrios Unidos',barrio = 'El Labrador',UPZ = '12 de Octubre' WHERE registro= 114;
UPDATE localidadesbogota SET registro = 115,localidad = 'Barrios Unidos',barrio = 'Metr�polis',UPZ = '12 de Octubre' WHERE registro= 115;
UPDATE localidadesbogota SET registro = 116,localidad = 'Barrios Unidos',barrio = 'San Fernando',UPZ = '12 de Octubre' WHERE registro= 116;
UPDATE localidadesbogota SET registro = 117,localidad = 'Barrios Unidos',barrio = 'La Merced Norte',UPZ = 'Los Alc�zares' WHERE registro= 117;
UPDATE localidadesbogota SET registro = 118,localidad = 'Barrios Unidos',barrio = 'Benjam�n Herrera',UPZ = 'Los Alc�zares' WHERE registro= 118;
UPDATE localidadesbogota SET registro = 119,localidad = 'Barrios Unidos',barrio = 'Concepci�n Norte',UPZ = 'Los Alc�zares' WHERE registro= 119;
UPDATE localidadesbogota SET registro = 120,localidad = 'Barrios Unidos',barrio = 'El Rosario',UPZ = 'Parque Salitre' WHERE registro= 120;
UPDATE localidadesbogota SET registro = 121,localidad = 'Teusaquillo',barrio = 'Banco Central',UPZ = 'Galer�as' WHERE registro= 121;
UPDATE localidadesbogota SET registro = 122,localidad = 'Teusaquillo',barrio = 'El Camp�n',UPZ = 'Galer�as' WHERE registro= 122;
UPDATE localidadesbogota SET registro = 123,localidad = 'Teusaquillo',barrio = 'Palermo',UPZ = 'Galer�as' WHERE registro= 123;
UPDATE localidadesbogota SET registro = 124,localidad = 'Teusaquillo',barrio = 'Pablo VI',UPZ = 'La Esmeralda' WHERE registro= 124;
UPDATE localidadesbogota SET registro = 125,localidad = 'Teusaquillo',barrio = 'Nicol�s de Federm�n',UPZ = 'La Esmeralda' WHERE registro= 125;
UPDATE localidadesbogota SET registro = 126,localidad = 'Teusaquillo',barrio = 'Acevedo Tejada',UPZ = 'Quinta Paredes' WHERE registro= 126;
UPDATE localidadesbogota SET registro = 127,localidad = 'Teusaquillo',barrio = 'Gran Am�rica',UPZ = 'Quinta Paredes' WHERE registro= 127;
UPDATE localidadesbogota SET registro = 128,localidad = 'Teusaquillo',barrio = 'Ciudad Salitre Nor-Oriental',UPZ = 'Ciudad Salitre Oriental' WHERE registro= 128;
UPDATE localidadesbogota SET registro = 129,localidad = 'Teusaquillo',barrio = 'Ciudad Salitre Sur Oriental',UPZ = 'Ciudad Salitre Oriental' WHERE registro= 129;
UPDATE localidadesbogota SET registro = 130,localidad = 'Teusaquillo',barrio = 'Parque Metropolitano Sim�n Bol�var',UPZ = 'Parque Sim�n Bol�var' WHERE registro= 130;
UPDATE localidadesbogota SET registro = 131,localidad = 'M�rtires',barrio = 'Eduardo Santos',UPZ = 'Santa Isabel' WHERE registro= 131;
UPDATE localidadesbogota SET registro = 132,localidad = 'M�rtires',barrio = 'El Progreso',UPZ = 'Santa Isabel' WHERE registro= 132;
UPDATE localidadesbogota SET registro = 133,localidad = 'M�rtires',barrio = 'El Vergel',UPZ = 'Santa Isabel' WHERE registro= 133;
UPDATE localidadesbogota SET registro = 134,localidad = 'M�rtires',barrio = 'Veraguas',UPZ = 'Santa Isabel' WHERE registro= 134;
UPDATE localidadesbogota SET registro = 135,localidad = 'M�rtires',barrio = 'Estaci�n de la Sabana',UPZ = 'La Sabana' WHERE registro= 135;
UPDATE localidadesbogota SET registro = 136,localidad = 'M�rtires',barrio = 'La Estanzuela',UPZ = 'La Sabana' WHERE registro= 136;
UPDATE localidadesbogota SET registro = 137,localidad = 'M�rtires',barrio = 'La Favorita',UPZ = 'La Sabana' WHERE registro= 137;
UPDATE localidadesbogota SET registro = 138,localidad = 'M�rtires',barrio = 'La Pepita',UPZ = 'La Sabana' WHERE registro= 138;
UPDATE localidadesbogota SET registro = 139,localidad = 'M�rtires',barrio = 'Ricaurte',UPZ = 'La Sabana' WHERE registro= 139;
UPDATE localidadesbogota SET registro = 140,localidad = 'M�rtires',barrio = 'Paloquemao',UPZ = 'La Sabana' WHERE registro= 140;
UPDATE localidadesbogota SET registro = 141,localidad = 'Antonio Nari�o',barrio = 'Villa Mayor',UPZ = 'Restrepo' WHERE registro= 141;
UPDATE localidadesbogota SET registro = 142,localidad = 'Antonio Nari�o',barrio = 'San Jorge Central',UPZ = 'Restrepo' WHERE registro= 142;
UPDATE localidadesbogota SET registro = 143,localidad = 'Antonio Nari�o',barrio = 'San Antonio',UPZ = 'Restrepo' WHERE registro= 143;
UPDATE localidadesbogota SET registro = 144,localidad = 'Antonio Nari�o',barrio = 'La Fragua',UPZ = 'Restrepo' WHERE registro= 144;
UPDATE localidadesbogota SET registro = 145,localidad = 'Antonio Nari�o',barrio = 'La Fraguita',UPZ = 'Restrepo' WHERE registro= 145;
UPDATE localidadesbogota SET registro = 146,localidad = 'Antonio Nari�o',barrio = 'Policarpa',UPZ = 'Ciudad Jard�n' WHERE registro= 146;
UPDATE localidadesbogota SET registro = 147,localidad = 'Antonio Nari�o',barrio = 'Ciudad Berna',UPZ = 'Ciudad Jard�n' WHERE registro= 147;
UPDATE localidadesbogota SET registro = 148,localidad = 'Antonio Nari�o',barrio = 'Sevilla',UPZ = 'Ciudad Jard�n' WHERE registro= 148;
UPDATE localidadesbogota SET registro = 149,localidad = 'Antonio Nari�o',barrio = 'Luna Park',UPZ = 'Ciudad Jard�n' WHERE registro= 149;
UPDATE localidadesbogota SET registro = 150,localidad = 'Antonio Nari�o',barrio = 'La Hort�a',UPZ = 'Ciudad Jard�n' WHERE registro= 150;
UPDATE localidadesbogota SET registro = 151,localidad = 'Puente Aranda',barrio = 'Alcal�',UPZ = 'Muz�' WHERE registro= 151;
UPDATE localidadesbogota SET registro = 152,localidad = 'Puente Aranda',barrio = 'Alquer�a',UPZ = 'Muz�' WHERE registro= 152;
UPDATE localidadesbogota SET registro = 153,localidad = 'Puente Aranda',barrio = 'Ospina P�rez',UPZ = 'Muz�' WHERE registro= 153;
UPDATE localidadesbogota SET registro = 154,localidad = 'Puente Aranda',barrio = 'Barcelona',UPZ = 'San Rafael' WHERE registro= 154;
UPDATE localidadesbogota SET registro = 155,localidad = 'Puente Aranda',barrio = 'Bisas del Gal�n',UPZ = 'San Rafael' WHERE registro= 155;
UPDATE localidadesbogota SET registro = 156,localidad = 'Puente Aranda',barrio = 'Cundinamarca',UPZ = 'Zona Industrial' WHERE registro= 156;
UPDATE localidadesbogota SET registro = 157,localidad = 'Puente Aranda',barrio = 'Gorgonzola',UPZ = 'Zona Industrial' WHERE registro= 157;
UPDATE localidadesbogota SET registro = 158,localidad = 'Puente Aranda',barrio = 'Batall�n Caldas',UPZ = 'Puente Aranda' WHERE registro= 158;
UPDATE localidadesbogota SET registro = 159,localidad = 'Puente Aranda',barrio = 'Centro Industrial',UPZ = 'Puente Aranda' WHERE registro= 159;
UPDATE localidadesbogota SET registro = 160,localidad = 'Puente Aranda',barrio = 'Ortezal',UPZ = 'Puente Aranda' WHERE registro= 160;
UPDATE localidadesbogota SET registro = 161,localidad = 'La Candelaria',barrio = 'La Catedral',UPZ = 'La Candelaria' WHERE registro= 161;
UPDATE localidadesbogota SET registro = 162,localidad = 'La Candelaria',barrio = 'La Concordia',UPZ = 'La Candelaria' WHERE registro= 162;
UPDATE localidadesbogota SET registro = 163,localidad = 'La Candelaria',barrio = 'Las Aguas',UPZ = 'La Candelaria' WHERE registro= 163;
UPDATE localidadesbogota SET registro = 164,localidad = 'La Candelaria',barrio = 'Centro Administrativo',UPZ = 'La Candelaria' WHERE registro= 164;
UPDATE localidadesbogota SET registro = 165,localidad = 'La Candelaria',barrio = 'Egipto',UPZ = 'La Candelaria' WHERE registro= 165;
UPDATE localidadesbogota SET registro = 166,localidad = 'La Candelaria',barrio = 'Bel�n',UPZ = 'La Candelaria' WHERE registro= 166;
UPDATE localidadesbogota SET registro = 167,localidad = 'La Candelaria',barrio = 'Nueva Santa Fe',UPZ = 'La Candelaria' WHERE registro= 167;
UPDATE localidadesbogota SET registro = 168,localidad = 'La Candelaria',barrio = 'Santa B�rbara',UPZ = 'La Candelaria' WHERE registro= 168;
UPDATE localidadesbogota SET registro = 169,localidad = 'Rafael Uribe',barrio = 'Claret',UPZ = 'Quiroga' WHERE registro= 169;
UPDATE localidadesbogota SET registro = 170,localidad = 'Rafael Uribe',barrio = 'Bravo P�ez',UPZ = 'Quiroga' WHERE registro= 170;
UPDATE localidadesbogota SET registro = 171,localidad = 'Rafael Uribe',barrio = 'Centenario',UPZ = 'Quiroga' WHERE registro= 171;
UPDATE localidadesbogota SET registro = 172,localidad = 'Rafael Uribe',barrio = 'Bosque de San Carlos',UPZ = 'San Jos�' WHERE registro= 172;
UPDATE localidadesbogota SET registro = 173,localidad = 'Rafael Uribe',barrio = 'Pijaos',UPZ = 'San Jos�' WHERE registro= 173;
UPDATE localidadesbogota SET registro = 174,localidad = 'Rafael Uribe',barrio = 'Granjas de Santa Sof�a',UPZ = 'Marco Fidel Su�rez' WHERE registro= 174;
UPDATE localidadesbogota SET registro = 175,localidad = 'Rafael Uribe',barrio = 'R�o de Janeiro',UPZ = 'Marco Fidel Su�rez' WHERE registro= 175;
UPDATE localidadesbogota SET registro = 176,localidad = 'Rafael Uribe',barrio = 'Arboleda Sur',UPZ = 'Marruecos' WHERE registro= 176;
UPDATE localidadesbogota SET registro = 177,localidad = 'Rafael Uribe',barrio = 'Chircales',UPZ = 'Marruecos' WHERE registro= 177;
UPDATE localidadesbogota SET registro = 178,localidad = 'Rafael Uribe',barrio = 'Villa Gladys',UPZ = 'Marruecos' WHERE registro= 178;
UPDATE localidadesbogota SET registro = 179,localidad = 'Ciudad Bol�var',barrio = 'La Lira',UPZ = 'El Mochuelo' WHERE registro= 179;
UPDATE localidadesbogota SET registro = 180,localidad = 'Ciudad Bol�var',barrio = 'El Pedregal',UPZ = 'El Mochuelo' WHERE registro= 180;
UPDATE localidadesbogota SET registro = 181,localidad = 'Ciudad Bol�var',barrio = 'Villa Jacky',UPZ = 'El Mochuelo' WHERE registro= 181;
UPDATE localidadesbogota SET registro = 182,localidad = 'Ciudad Bol�var',barrio = 'Brazuelos de Santo Domingo',UPZ = 'Monteblanco' WHERE registro= 182;
UPDATE localidadesbogota SET registro = 183,localidad = 'Ciudad Bol�var',barrio = 'Paticos',UPZ = 'Monteblanco' WHERE registro= 183;
UPDATE localidadesbogota SET registro = 184,localidad = 'Ciudad Bol�var',barrio = 'Arborizadora Baja',UPZ = 'Arborizadora' WHERE registro= 184;
UPDATE localidadesbogota SET registro = 185,localidad = 'Ciudad Bol�var',barrio = 'Arborizadora Alta',UPZ = 'Arborizadora' WHERE registro= 185;
UPDATE localidadesbogota SET registro = 186,localidad = 'Ciudad Bol�var',barrio = 'Las Acacias',UPZ = 'San Francisco' WHERE registro= 186;
UPDATE localidadesbogota SET registro = 187,localidad = 'Ciudad Bol�var',barrio = 'Gibraltar',UPZ = 'San Francisco' WHERE registro= 187;
UPDATE localidadesbogota SET registro = 188,localidad = 'Ciudad Bol�var',barrio = 'La Casona',UPZ = 'San Francisco' WHERE registro= 188;
